### ISSUE TITLE
Add progress bar 

### ISSUE THREAD

**Issue by julienOlivier3** [till-tietz/parsel#1]
Hey Till,

I really like your package and I think it is a great contribution to scale webscraping tasks that rely on Selenium. One useful addition would be a progress bar or something related that allows to track how much percent of the input vector's elements have been processed already (and how much time is expected until finishing the whole scraping process).

From your source code this would seem to be a rather minor adjustment (given that you already print finalized chunks). Maybe pbapply::pblapply() would be a solution - but not sure about the overhead that is caused due to parallelization.

Anyways, thanks for this nice piece of software.

Best
Julian

**Comment by till-tietz** [comment]
Hi Julian,

I'm really happy to hear that the package is proving useful. Thank you for the great suggestion; a progress bar/expected finish time would be a really nice feature. I'll have a look into maybe implementing a progress bar directly in the for loop with something like svMisc::progress(). I'll also see if I can print an estimated finish time. Thanks again for the comment. 

Cheers, 

Till

**Comment by till-tietz** [comment]
Added progress bar and estimated remaining run time output to parscrape.
