### ISSUE TITLE
`arguments imply differing number of rows` error with parscrape function

### ISSUE THREAD

**Issue by KanKuno** [till-tietz/parsel#38]
Hi Till,

I am really enjoying your package and it is helping me a lot to scrape a large amount of data.
I just wanted to mention that I found something like a bug in the parscrape function (and I am not an experienced GitHub user so my apologies if I am posting on the wrong place).

I was trying your Wikipedia example which for some reason seems to always return results as unscraped.
Maybe the HTML source has changed, but that's not what I wanted to point out.
I first ran your example code as exactly as it is with 4 inputs, and as expected, `wiki_text$not_scraped` is a dataframe with 4 rows.
Then I tried with 5, so I only changed `input <- rep("https://de.wikipedia.org",4)` to `input <- rep("https://de.wikipedia.org",5)`.
Now I am getting an error 
`Error in data.frame(element_input_id = unlist(chunks[unscraped_chunks]),  : 
  arguments imply differing number of rows: 5, 6`
I was wondering if it's because of the following lines of your parscape function:
`unscraped <- data.frame(element_input_id = unlist(chunks[unscraped_chunks]), 
    element_chunk = rep(unscraped_chunks, each = chunk_size), 
    error = rep(unlist(error_list), each = chunk_size))`

Sorry if I am wrong but I wanted to mention this since I was running into the same error when I use the function on my own project. 
Anyways thank you very much for the exciting package. You saved my life!

Best,
Kan

**Comment by till-tietz** [comment]
Hi Kan, 

I'm glad to hear you're enjoying the package. Thanks for reporting this; I'll check this out asap today and run some tests.

Cheers, 

Till

**Comment by till-tietz** [comment]
Hi Kan, 

the bug should be resolved in 39ba12f . Thanks again for pointing this out, you pin-pointed the exact location of the issue. Let me know if things work on your end with the patched development version from github. I'll push a patch release with the fix to CRAN tomorrow. 

Cheers, 

Till

**Comment by KanKuno** [comment]
Hi Till, 

Yes, the new version is working perfectly on my end as well, thanks!

Best,
Kan

**Comment by till-tietz** [comment]
Fantastic!!! Patched version is on CRAN. Marking the issue as resolved.
